name: allcareapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_secure_storage: 4.2.1
  image_picker: 0.7.5
  cupertino_icons: ^1.0.2
  package_info: 0.4.1
  flavor_config: 1.3.0
  flutter_bloc: 7.0.0
#  firebase_core: 1.0.4
#  firebase_performance: 0.6.0+2
#  firebase_analytics: 7.1.1
#  firebase_crashlytics: 1.0.0
#  firebase_messaging: 9.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/user.png